version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - whitespace
    - gocritic

  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
    goimports:
      local-prefixes: github.com/mandacode-labs/dodream
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: unexported-return
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - dupl
        path: _test\.go
      - linters:
          - all
        path: ent/
        text: ".*"
    paths:
      - ent/
      - vendor/

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
    goimports:
      local-prefixes: github.com/mandacode-labs/dodream
  exclusions:
    generated: lax
    paths:
      - ent/
      - vendor/
