all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{lower .InterfaceName}}.go"
structname: "{{.InterfaceName}}Mock"
pkgname: "{{.SrcPackageName}}mocks"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/mandacode-labs/dodream/internal/user:
    interfaces:
      Repository:
  github.com/mandacode-labs/dodream/internal/card:
    interfaces:
      Repository:
  github.com/mandacode-labs/dodream/internal/deck:
    interfaces:
      Repository:
  github.com/mandacode-labs/dodream/internal/collection:
    interfaces:
      Repository:
  github.com/mandacode-labs/dodream/internal/studyevent:
    interfaces:
      Repository:
  github.com/mandacode-labs/dodream/internal/engine/state:
    interfaces:
      Repository: