// Code generated by ogen, DO NOT EDIT.
package api

type DeleteCardRes interface {
	deleteCardRes()
}

type DeleteCollectionRes interface {
	deleteCollectionRes()
}

type DeleteDeckRes interface {
	deleteDeckRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetCardRes interface {
	getCardRes()
}

type GetCollectionRes interface {
	getCollectionRes()
}

type GetDeckRes interface {
	getDeckRes()
}

type GetUserRes interface {
	getUserRes()
}

type UpdateCardRes interface {
	updateCardRes()
}

type UpdateCollectionRes interface {
	updateCollectionRes()
}

type UpdateDeckRes interface {
	updateDeckRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
