// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CardsColumns holds the columns for the "cards" table.
	CardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "hint", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_cards", Type: field.TypeString},
	}
	// CardsTable holds the schema information for the "cards" table.
	CardsTable = &schema.Table{
		Name:       "cards",
		Columns:    CardsColumns,
		PrimaryKey: []*schema.Column{CardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cards_users_cards",
				Columns:    []*schema.Column{CardsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DecksColumns holds the columns for the "decks" table.
	DecksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_decks", Type: field.TypeString},
	}
	// DecksTable holds the schema information for the "decks" table.
	DecksTable = &schema.Table{
		Name:       "decks",
		Columns:    DecksColumns,
		PrimaryKey: []*schema.Column{DecksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "decks_users_decks",
				Columns:    []*schema.Column{DecksColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// NotebooksColumns holds the columns for the "notebooks" table.
	NotebooksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_notebooks", Type: field.TypeString},
	}
	// NotebooksTable holds the schema information for the "notebooks" table.
	NotebooksTable = &schema.Table{
		Name:       "notebooks",
		Columns:    NotebooksColumns,
		PrimaryKey: []*schema.Column{NotebooksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notebooks_users_notebooks",
				Columns:    []*schema.Column{NotebooksColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// NotebookCardsColumns holds the columns for the "notebook_cards" table.
	NotebookCardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "card_notebook_cards", Type: field.TypeString},
		{Name: "deck_notebook_cards", Type: field.TypeString, Nullable: true},
		{Name: "notebook_notebook_cards", Type: field.TypeString},
	}
	// NotebookCardsTable holds the schema information for the "notebook_cards" table.
	NotebookCardsTable = &schema.Table{
		Name:       "notebook_cards",
		Columns:    NotebookCardsColumns,
		PrimaryKey: []*schema.Column{NotebookCardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notebook_cards_cards_notebook_cards",
				Columns:    []*schema.Column{NotebookCardsColumns[3]},
				RefColumns: []*schema.Column{CardsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "notebook_cards_decks_notebook_cards",
				Columns:    []*schema.Column{NotebookCardsColumns[4]},
				RefColumns: []*schema.Column{DecksColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "notebook_cards_notebooks_notebook_cards",
				Columns:    []*schema.Column{NotebookCardsColumns[5]},
				RefColumns: []*schema.Column{NotebooksColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "nickname", Type: field.TypeString},
		{Name: "provider_id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// CardDecksColumns holds the columns for the "card_decks" table.
	CardDecksColumns = []*schema.Column{
		{Name: "card_id", Type: field.TypeString},
		{Name: "deck_id", Type: field.TypeString},
	}
	// CardDecksTable holds the schema information for the "card_decks" table.
	CardDecksTable = &schema.Table{
		Name:       "card_decks",
		Columns:    CardDecksColumns,
		PrimaryKey: []*schema.Column{CardDecksColumns[0], CardDecksColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "card_decks_card_id",
				Columns:    []*schema.Column{CardDecksColumns[0]},
				RefColumns: []*schema.Column{CardsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "card_decks_deck_id",
				Columns:    []*schema.Column{CardDecksColumns[1]},
				RefColumns: []*schema.Column{DecksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CardsTable,
		DecksTable,
		NotebooksTable,
		NotebookCardsTable,
		UsersTable,
		CardDecksTable,
	}
)

func init() {
	CardsTable.ForeignKeys[0].RefTable = UsersTable
	DecksTable.ForeignKeys[0].RefTable = UsersTable
	NotebooksTable.ForeignKeys[0].RefTable = UsersTable
	NotebookCardsTable.ForeignKeys[0].RefTable = CardsTable
	NotebookCardsTable.ForeignKeys[1].RefTable = DecksTable
	NotebookCardsTable.ForeignKeys[2].RefTable = NotebooksTable
	CardDecksTable.ForeignKeys[0].RefTable = CardsTable
	CardDecksTable.ForeignKeys[1].RefTable = DecksTable
}
