// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-labs/dodream/ent/card"
	"github.com/mandacode-labs/dodream/ent/collectioncard"
	"github.com/mandacode-labs/dodream/ent/deck"
	"github.com/mandacode-labs/dodream/ent/predicate"
	"github.com/mandacode-labs/dodream/ent/studyevent"
	"github.com/mandacode-labs/dodream/ent/user"
)

// CardUpdate is the builder for updating Card entities.
type CardUpdate struct {
	config
	hooks    []Hook
	mutation *CardMutation
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdate) Where(ps ...predicate.Card) *CardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestion sets the "question" field.
func (_u *CardUpdate) SetQuestion(v string) *CardUpdate {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *CardUpdate) SetNillableQuestion(v *string) *CardUpdate {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetHint sets the "hint" field.
func (_u *CardUpdate) SetHint(v string) *CardUpdate {
	_u.mutation.SetHint(v)
	return _u
}

// SetNillableHint sets the "hint" field if the given value is not nil.
func (_u *CardUpdate) SetNillableHint(v *string) *CardUpdate {
	if v != nil {
		_u.SetHint(*v)
	}
	return _u
}

// ClearHint clears the value of the "hint" field.
func (_u *CardUpdate) ClearHint() *CardUpdate {
	_u.mutation.ClearHint()
	return _u
}

// SetContent sets the "content" field.
func (_u *CardUpdate) SetContent(v string) *CardUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CardUpdate) SetNillableContent(v *string) *CardUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardUpdate) SetUpdatedAt(v time.Time) *CardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *CardUpdate) SetCreatorID(id string) *CardUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *CardUpdate) SetCreator(v *User) *CardUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddDeckIDs adds the "decks" edge to the Deck entity by IDs.
func (_u *CardUpdate) AddDeckIDs(ids ...string) *CardUpdate {
	_u.mutation.AddDeckIDs(ids...)
	return _u
}

// AddDecks adds the "decks" edges to the Deck entity.
func (_u *CardUpdate) AddDecks(v ...*Deck) *CardUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeckIDs(ids...)
}

// AddCollectionCardIDs adds the "collection_cards" edge to the CollectionCard entity by IDs.
func (_u *CardUpdate) AddCollectionCardIDs(ids ...string) *CardUpdate {
	_u.mutation.AddCollectionCardIDs(ids...)
	return _u
}

// AddCollectionCards adds the "collection_cards" edges to the CollectionCard entity.
func (_u *CardUpdate) AddCollectionCards(v ...*CollectionCard) *CardUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionCardIDs(ids...)
}

// AddStudyEventIDs adds the "study_events" edge to the StudyEvent entity by IDs.
func (_u *CardUpdate) AddStudyEventIDs(ids ...string) *CardUpdate {
	_u.mutation.AddStudyEventIDs(ids...)
	return _u
}

// AddStudyEvents adds the "study_events" edges to the StudyEvent entity.
func (_u *CardUpdate) AddStudyEvents(v ...*StudyEvent) *CardUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudyEventIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdate) Mutation() *CardMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *CardUpdate) ClearCreator() *CardUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearDecks clears all "decks" edges to the Deck entity.
func (_u *CardUpdate) ClearDecks() *CardUpdate {
	_u.mutation.ClearDecks()
	return _u
}

// RemoveDeckIDs removes the "decks" edge to Deck entities by IDs.
func (_u *CardUpdate) RemoveDeckIDs(ids ...string) *CardUpdate {
	_u.mutation.RemoveDeckIDs(ids...)
	return _u
}

// RemoveDecks removes "decks" edges to Deck entities.
func (_u *CardUpdate) RemoveDecks(v ...*Deck) *CardUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeckIDs(ids...)
}

// ClearCollectionCards clears all "collection_cards" edges to the CollectionCard entity.
func (_u *CardUpdate) ClearCollectionCards() *CardUpdate {
	_u.mutation.ClearCollectionCards()
	return _u
}

// RemoveCollectionCardIDs removes the "collection_cards" edge to CollectionCard entities by IDs.
func (_u *CardUpdate) RemoveCollectionCardIDs(ids ...string) *CardUpdate {
	_u.mutation.RemoveCollectionCardIDs(ids...)
	return _u
}

// RemoveCollectionCards removes "collection_cards" edges to CollectionCard entities.
func (_u *CardUpdate) RemoveCollectionCards(v ...*CollectionCard) *CardUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionCardIDs(ids...)
}

// ClearStudyEvents clears all "study_events" edges to the StudyEvent entity.
func (_u *CardUpdate) ClearStudyEvents() *CardUpdate {
	_u.mutation.ClearStudyEvents()
	return _u
}

// RemoveStudyEventIDs removes the "study_events" edge to StudyEvent entities by IDs.
func (_u *CardUpdate) RemoveStudyEventIDs(ids ...string) *CardUpdate {
	_u.mutation.RemoveStudyEventIDs(ids...)
	return _u
}

// RemoveStudyEvents removes "study_events" edges to StudyEvent entities.
func (_u *CardUpdate) RemoveStudyEvents(v ...*StudyEvent) *CardUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudyEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := card.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdate) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := card.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "Card.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := card.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Card.content": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.creator"`)
	}
	return nil
}

func (_u *CardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(card.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hint(); ok {
		_spec.SetField(card.FieldHint, field.TypeString, value)
	}
	if _u.mutation.HintCleared() {
		_spec.ClearField(card.FieldHint, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(card.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.CreatorTable,
			Columns: []string{card.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.CreatorTable,
			Columns: []string{card.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.DecksTable,
			Columns: card.DecksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDecksIDs(); len(nodes) > 0 && !_u.mutation.DecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.DecksTable,
			Columns: card.DecksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.DecksTable,
			Columns: card.DecksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.CollectionCardsTable,
			Columns: []string{card.CollectionCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionCardsIDs(); len(nodes) > 0 && !_u.mutation.CollectionCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.CollectionCardsTable,
			Columns: []string{card.CollectionCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.CollectionCardsTable,
			Columns: []string{card.CollectionCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.StudyEventsTable,
			Columns: []string{card.StudyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(studyevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudyEventsIDs(); len(nodes) > 0 && !_u.mutation.StudyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.StudyEventsTable,
			Columns: []string{card.StudyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(studyevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudyEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.StudyEventsTable,
			Columns: []string{card.StudyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(studyevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardUpdateOne is the builder for updating a single Card entity.
type CardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardMutation
}

// SetQuestion sets the "question" field.
func (_u *CardUpdateOne) SetQuestion(v string) *CardUpdateOne {
	_u.mutation.SetQuestion(v)
	return _u
}

// SetNillableQuestion sets the "question" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableQuestion(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetQuestion(*v)
	}
	return _u
}

// SetHint sets the "hint" field.
func (_u *CardUpdateOne) SetHint(v string) *CardUpdateOne {
	_u.mutation.SetHint(v)
	return _u
}

// SetNillableHint sets the "hint" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableHint(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetHint(*v)
	}
	return _u
}

// ClearHint clears the value of the "hint" field.
func (_u *CardUpdateOne) ClearHint() *CardUpdateOne {
	_u.mutation.ClearHint()
	return _u
}

// SetContent sets the "content" field.
func (_u *CardUpdateOne) SetContent(v string) *CardUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CardUpdateOne) SetNillableContent(v *string) *CardUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardUpdateOne) SetUpdatedAt(v time.Time) *CardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *CardUpdateOne) SetCreatorID(id string) *CardUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *CardUpdateOne) SetCreator(v *User) *CardUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddDeckIDs adds the "decks" edge to the Deck entity by IDs.
func (_u *CardUpdateOne) AddDeckIDs(ids ...string) *CardUpdateOne {
	_u.mutation.AddDeckIDs(ids...)
	return _u
}

// AddDecks adds the "decks" edges to the Deck entity.
func (_u *CardUpdateOne) AddDecks(v ...*Deck) *CardUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeckIDs(ids...)
}

// AddCollectionCardIDs adds the "collection_cards" edge to the CollectionCard entity by IDs.
func (_u *CardUpdateOne) AddCollectionCardIDs(ids ...string) *CardUpdateOne {
	_u.mutation.AddCollectionCardIDs(ids...)
	return _u
}

// AddCollectionCards adds the "collection_cards" edges to the CollectionCard entity.
func (_u *CardUpdateOne) AddCollectionCards(v ...*CollectionCard) *CardUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCollectionCardIDs(ids...)
}

// AddStudyEventIDs adds the "study_events" edge to the StudyEvent entity by IDs.
func (_u *CardUpdateOne) AddStudyEventIDs(ids ...string) *CardUpdateOne {
	_u.mutation.AddStudyEventIDs(ids...)
	return _u
}

// AddStudyEvents adds the "study_events" edges to the StudyEvent entity.
func (_u *CardUpdateOne) AddStudyEvents(v ...*StudyEvent) *CardUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStudyEventIDs(ids...)
}

// Mutation returns the CardMutation object of the builder.
func (_u *CardUpdateOne) Mutation() *CardMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *CardUpdateOne) ClearCreator() *CardUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearDecks clears all "decks" edges to the Deck entity.
func (_u *CardUpdateOne) ClearDecks() *CardUpdateOne {
	_u.mutation.ClearDecks()
	return _u
}

// RemoveDeckIDs removes the "decks" edge to Deck entities by IDs.
func (_u *CardUpdateOne) RemoveDeckIDs(ids ...string) *CardUpdateOne {
	_u.mutation.RemoveDeckIDs(ids...)
	return _u
}

// RemoveDecks removes "decks" edges to Deck entities.
func (_u *CardUpdateOne) RemoveDecks(v ...*Deck) *CardUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeckIDs(ids...)
}

// ClearCollectionCards clears all "collection_cards" edges to the CollectionCard entity.
func (_u *CardUpdateOne) ClearCollectionCards() *CardUpdateOne {
	_u.mutation.ClearCollectionCards()
	return _u
}

// RemoveCollectionCardIDs removes the "collection_cards" edge to CollectionCard entities by IDs.
func (_u *CardUpdateOne) RemoveCollectionCardIDs(ids ...string) *CardUpdateOne {
	_u.mutation.RemoveCollectionCardIDs(ids...)
	return _u
}

// RemoveCollectionCards removes "collection_cards" edges to CollectionCard entities.
func (_u *CardUpdateOne) RemoveCollectionCards(v ...*CollectionCard) *CardUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCollectionCardIDs(ids...)
}

// ClearStudyEvents clears all "study_events" edges to the StudyEvent entity.
func (_u *CardUpdateOne) ClearStudyEvents() *CardUpdateOne {
	_u.mutation.ClearStudyEvents()
	return _u
}

// RemoveStudyEventIDs removes the "study_events" edge to StudyEvent entities by IDs.
func (_u *CardUpdateOne) RemoveStudyEventIDs(ids ...string) *CardUpdateOne {
	_u.mutation.RemoveStudyEventIDs(ids...)
	return _u
}

// RemoveStudyEvents removes "study_events" edges to StudyEvent entities.
func (_u *CardUpdateOne) RemoveStudyEvents(v ...*StudyEvent) *CardUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStudyEventIDs(ids...)
}

// Where appends a list predicates to the CardUpdate builder.
func (_u *CardUpdateOne) Where(ps ...predicate.Card) *CardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardUpdateOne) Select(field string, fields ...string) *CardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Card entity.
func (_u *CardUpdateOne) Save(ctx context.Context) (*Card, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardUpdateOne) SaveX(ctx context.Context) *Card {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := card.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardUpdateOne) check() error {
	if v, ok := _u.mutation.Question(); ok {
		if err := card.QuestionValidator(v); err != nil {
			return &ValidationError{Name: "question", err: fmt.Errorf(`ent: validator failed for field "Card.question": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := card.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Card.content": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Card.creator"`)
	}
	return nil
}

func (_u *CardUpdateOne) sqlSave(ctx context.Context) (_node *Card, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(card.Table, card.Columns, sqlgraph.NewFieldSpec(card.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Card.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, card.FieldID)
		for _, f := range fields {
			if !card.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != card.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Question(); ok {
		_spec.SetField(card.FieldQuestion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hint(); ok {
		_spec.SetField(card.FieldHint, field.TypeString, value)
	}
	if _u.mutation.HintCleared() {
		_spec.ClearField(card.FieldHint, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(card.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(card.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.CreatorTable,
			Columns: []string{card.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   card.CreatorTable,
			Columns: []string{card.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.DecksTable,
			Columns: card.DecksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDecksIDs(); len(nodes) > 0 && !_u.mutation.DecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.DecksTable,
			Columns: card.DecksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   card.DecksTable,
			Columns: card.DecksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.CollectionCardsTable,
			Columns: []string{card.CollectionCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCollectionCardsIDs(); len(nodes) > 0 && !_u.mutation.CollectionCardsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.CollectionCardsTable,
			Columns: []string{card.CollectionCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionCardsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.CollectionCardsTable,
			Columns: []string{card.CollectionCardsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StudyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.StudyEventsTable,
			Columns: []string{card.StudyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(studyevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStudyEventsIDs(); len(nodes) > 0 && !_u.mutation.StudyEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.StudyEventsTable,
			Columns: []string{card.StudyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(studyevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StudyEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   card.StudyEventsTable,
			Columns: []string{card.StudyEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(studyevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Card{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{card.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
