// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mandacode-labs/dodream/ent/card"
	"github.com/mandacode-labs/dodream/ent/user"
)

// Card is the model entity for the Card schema.
type Card struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// Hint holds the value of the "hint" field.
	Hint string `json:"hint,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CardQuery when eager-loading is set.
	Edges        CardEdges `json:"edges"`
	user_cards   *string
	selectValues sql.SelectValues
}

// CardEdges holds the relations/edges for other nodes in the graph.
type CardEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Decks holds the value of the decks edge.
	Decks []*Deck `json:"decks,omitempty"`
	// CollectionCards holds the value of the collection_cards edge.
	CollectionCards []*CollectionCard `json:"collection_cards,omitempty"`
	// StudyEvents holds the value of the study_events edge.
	StudyEvents []*StudyEvent `json:"study_events,omitempty"`
	// States holds the value of the states edge.
	States []*State `json:"states,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CardEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// DecksOrErr returns the Decks value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) DecksOrErr() ([]*Deck, error) {
	if e.loadedTypes[1] {
		return e.Decks, nil
	}
	return nil, &NotLoadedError{edge: "decks"}
}

// CollectionCardsOrErr returns the CollectionCards value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) CollectionCardsOrErr() ([]*CollectionCard, error) {
	if e.loadedTypes[2] {
		return e.CollectionCards, nil
	}
	return nil, &NotLoadedError{edge: "collection_cards"}
}

// StudyEventsOrErr returns the StudyEvents value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) StudyEventsOrErr() ([]*StudyEvent, error) {
	if e.loadedTypes[3] {
		return e.StudyEvents, nil
	}
	return nil, &NotLoadedError{edge: "study_events"}
}

// StatesOrErr returns the States value or an error if the edge
// was not loaded in eager-loading.
func (e CardEdges) StatesOrErr() ([]*State, error) {
	if e.loadedTypes[4] {
		return e.States, nil
	}
	return nil, &NotLoadedError{edge: "states"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Card) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case card.FieldID, card.FieldQuestion, card.FieldHint, card.FieldContent:
			values[i] = new(sql.NullString)
		case card.FieldCreatedAt, card.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case card.ForeignKeys[0]: // user_cards
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Card fields.
func (_m *Card) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case card.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case card.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				_m.Question = value.String
			}
		case card.FieldHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hint", values[i])
			} else if value.Valid {
				_m.Hint = value.String
			}
		case card.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case card.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case card.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case card.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_cards", values[i])
			} else if value.Valid {
				_m.user_cards = new(string)
				*_m.user_cards = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Card.
// This includes values selected through modifiers, order, etc.
func (_m *Card) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Card entity.
func (_m *Card) QueryCreator() *UserQuery {
	return NewCardClient(_m.config).QueryCreator(_m)
}

// QueryDecks queries the "decks" edge of the Card entity.
func (_m *Card) QueryDecks() *DeckQuery {
	return NewCardClient(_m.config).QueryDecks(_m)
}

// QueryCollectionCards queries the "collection_cards" edge of the Card entity.
func (_m *Card) QueryCollectionCards() *CollectionCardQuery {
	return NewCardClient(_m.config).QueryCollectionCards(_m)
}

// QueryStudyEvents queries the "study_events" edge of the Card entity.
func (_m *Card) QueryStudyEvents() *StudyEventQuery {
	return NewCardClient(_m.config).QueryStudyEvents(_m)
}

// QueryStates queries the "states" edge of the Card entity.
func (_m *Card) QueryStates() *StateQuery {
	return NewCardClient(_m.config).QueryStates(_m)
}

// Update returns a builder for updating this Card.
// Note that you need to call Card.Unwrap() before calling this method if this Card
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Card) Update() *CardUpdateOne {
	return NewCardClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Card entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Card) Unwrap() *Card {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Card is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Card) String() string {
	var builder strings.Builder
	builder.WriteString("Card(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("question=")
	builder.WriteString(_m.Question)
	builder.WriteString(", ")
	builder.WriteString("hint=")
	builder.WriteString(_m.Hint)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Cards is a parsable slice of Card.
type Cards []*Card
