// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-labs/dodream/ent/collectioncard"
	"github.com/mandacode-labs/dodream/ent/predicate"
)

// CollectionCardDelete is the builder for deleting a CollectionCard entity.
type CollectionCardDelete struct {
	config
	hooks    []Hook
	mutation *CollectionCardMutation
}

// Where appends a list predicates to the CollectionCardDelete builder.
func (_d *CollectionCardDelete) Where(ps ...predicate.CollectionCard) *CollectionCardDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CollectionCardDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollectionCardDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CollectionCardDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(collectioncard.Table, sqlgraph.NewFieldSpec(collectioncard.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CollectionCardDeleteOne is the builder for deleting a single CollectionCard entity.
type CollectionCardDeleteOne struct {
	_d *CollectionCardDelete
}

// Where appends a list predicates to the CollectionCardDelete builder.
func (_d *CollectionCardDeleteOne) Where(ps ...predicate.CollectionCard) *CollectionCardDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CollectionCardDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{collectioncard.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CollectionCardDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
