// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-labs/dodream/ent/eventprocessing"
	"github.com/mandacode-labs/dodream/ent/predicate"
)

// EventProcessingDelete is the builder for deleting a EventProcessing entity.
type EventProcessingDelete struct {
	config
	hooks    []Hook
	mutation *EventProcessingMutation
}

// Where appends a list predicates to the EventProcessingDelete builder.
func (_d *EventProcessingDelete) Where(ps ...predicate.EventProcessing) *EventProcessingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EventProcessingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EventProcessingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EventProcessingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventprocessing.Table, sqlgraph.NewFieldSpec(eventprocessing.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EventProcessingDeleteOne is the builder for deleting a single EventProcessing entity.
type EventProcessingDeleteOne struct {
	_d *EventProcessingDelete
}

// Where appends a list predicates to the EventProcessingDelete builder.
func (_d *EventProcessingDeleteOne) Where(ps ...predicate.EventProcessing) *EventProcessingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EventProcessingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventprocessing.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EventProcessingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
