// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mandacode-labs/dodream/ent/card"
	"github.com/mandacode-labs/dodream/ent/deck"
	"github.com/mandacode-labs/dodream/ent/notebook"
	"github.com/mandacode-labs/dodream/ent/notebookcard"
	"github.com/mandacode-labs/dodream/ent/predicate"
	"github.com/mandacode-labs/dodream/ent/user"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCard         = "Card"
	TypeDeck         = "Deck"
	TypeNotebook     = "Notebook"
	TypeNotebookCard = "NotebookCard"
	TypeUser         = "User"
)

// CardMutation represents an operation that mutates the Card nodes in the graph.
type CardMutation struct {
	config
	op                    Op
	typ                   string
	id                    *string
	hint                  *string
	content               *string
	created_at            *time.Time
	updated_at            *time.Time
	clearedFields         map[string]struct{}
	creator               *string
	clearedcreator        bool
	decks                 map[string]struct{}
	removeddecks          map[string]struct{}
	cleareddecks          bool
	notebook_cards        map[string]struct{}
	removednotebook_cards map[string]struct{}
	clearednotebook_cards bool
	done                  bool
	oldValue              func(context.Context) (*Card, error)
	predicates            []predicate.Card
}

var _ ent.Mutation = (*CardMutation)(nil)

// cardOption allows management of the mutation configuration using functional options.
type cardOption func(*CardMutation)

// newCardMutation creates new mutation for the Card entity.
func newCardMutation(c config, op Op, opts ...cardOption) *CardMutation {
	m := &CardMutation{
		config:        c,
		op:            op,
		typ:           TypeCard,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCardID sets the ID field of the mutation.
func withCardID(id string) cardOption {
	return func(m *CardMutation) {
		var (
			err   error
			once  sync.Once
			value *Card
		)
		m.oldValue = func(ctx context.Context) (*Card, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Card.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCard sets the old Card of the mutation.
func withCard(node *Card) cardOption {
	return func(m *CardMutation) {
		m.oldValue = func(context.Context) (*Card, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CardMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CardMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Card entities.
func (m *CardMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CardMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CardMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Card.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetHint sets the "hint" field.
func (m *CardMutation) SetHint(s string) {
	m.hint = &s
}

// Hint returns the value of the "hint" field in the mutation.
func (m *CardMutation) Hint() (r string, exists bool) {
	v := m.hint
	if v == nil {
		return
	}
	return *v, true
}

// OldHint returns the old "hint" field's value of the Card entity.
// If the Card object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CardMutation) OldHint(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHint: %w", err)
	}
	return oldValue.Hint, nil
}

// ClearHint clears the value of the "hint" field.
func (m *CardMutation) ClearHint() {
	m.hint = nil
	m.clearedFields[card.FieldHint] = struct{}{}
}

// HintCleared returns if the "hint" field was cleared in this mutation.
func (m *CardMutation) HintCleared() bool {
	_, ok := m.clearedFields[card.FieldHint]
	return ok
}

// ResetHint resets all changes to the "hint" field.
func (m *CardMutation) ResetHint() {
	m.hint = nil
	delete(m.clearedFields, card.FieldHint)
}

// SetContent sets the "content" field.
func (m *CardMutation) SetContent(s string) {
	m.content = &s
}

// Content returns the value of the "content" field in the mutation.
func (m *CardMutation) Content() (r string, exists bool) {
	v := m.content
	if v == nil {
		return
	}
	return *v, true
}

// OldContent returns the old "content" field's value of the Card entity.
// If the Card object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CardMutation) OldContent(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContent: %w", err)
	}
	return oldValue.Content, nil
}

// ResetContent resets all changes to the "content" field.
func (m *CardMutation) ResetContent() {
	m.content = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *CardMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CardMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Card entity.
// If the Card object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CardMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CardMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *CardMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *CardMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Card entity.
// If the Card object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CardMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *CardMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetCreatorID sets the "creator" edge to the User entity by id.
func (m *CardMutation) SetCreatorID(id string) {
	m.creator = &id
}

// ClearCreator clears the "creator" edge to the User entity.
func (m *CardMutation) ClearCreator() {
	m.clearedcreator = true
}

// CreatorCleared reports if the "creator" edge to the User entity was cleared.
func (m *CardMutation) CreatorCleared() bool {
	return m.clearedcreator
}

// CreatorID returns the "creator" edge ID in the mutation.
func (m *CardMutation) CreatorID() (id string, exists bool) {
	if m.creator != nil {
		return *m.creator, true
	}
	return
}

// CreatorIDs returns the "creator" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CreatorID instead. It exists only for internal usage by the builders.
func (m *CardMutation) CreatorIDs() (ids []string) {
	if id := m.creator; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCreator resets all changes to the "creator" edge.
func (m *CardMutation) ResetCreator() {
	m.creator = nil
	m.clearedcreator = false
}

// AddDeckIDs adds the "decks" edge to the Deck entity by ids.
func (m *CardMutation) AddDeckIDs(ids ...string) {
	if m.decks == nil {
		m.decks = make(map[string]struct{})
	}
	for i := range ids {
		m.decks[ids[i]] = struct{}{}
	}
}

// ClearDecks clears the "decks" edge to the Deck entity.
func (m *CardMutation) ClearDecks() {
	m.cleareddecks = true
}

// DecksCleared reports if the "decks" edge to the Deck entity was cleared.
func (m *CardMutation) DecksCleared() bool {
	return m.cleareddecks
}

// RemoveDeckIDs removes the "decks" edge to the Deck entity by IDs.
func (m *CardMutation) RemoveDeckIDs(ids ...string) {
	if m.removeddecks == nil {
		m.removeddecks = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.decks, ids[i])
		m.removeddecks[ids[i]] = struct{}{}
	}
}

// RemovedDecks returns the removed IDs of the "decks" edge to the Deck entity.
func (m *CardMutation) RemovedDecksIDs() (ids []string) {
	for id := range m.removeddecks {
		ids = append(ids, id)
	}
	return
}

// DecksIDs returns the "decks" edge IDs in the mutation.
func (m *CardMutation) DecksIDs() (ids []string) {
	for id := range m.decks {
		ids = append(ids, id)
	}
	return
}

// ResetDecks resets all changes to the "decks" edge.
func (m *CardMutation) ResetDecks() {
	m.decks = nil
	m.cleareddecks = false
	m.removeddecks = nil
}

// AddNotebookCardIDs adds the "notebook_cards" edge to the NotebookCard entity by ids.
func (m *CardMutation) AddNotebookCardIDs(ids ...string) {
	if m.notebook_cards == nil {
		m.notebook_cards = make(map[string]struct{})
	}
	for i := range ids {
		m.notebook_cards[ids[i]] = struct{}{}
	}
}

// ClearNotebookCards clears the "notebook_cards" edge to the NotebookCard entity.
func (m *CardMutation) ClearNotebookCards() {
	m.clearednotebook_cards = true
}

// NotebookCardsCleared reports if the "notebook_cards" edge to the NotebookCard entity was cleared.
func (m *CardMutation) NotebookCardsCleared() bool {
	return m.clearednotebook_cards
}

// RemoveNotebookCardIDs removes the "notebook_cards" edge to the NotebookCard entity by IDs.
func (m *CardMutation) RemoveNotebookCardIDs(ids ...string) {
	if m.removednotebook_cards == nil {
		m.removednotebook_cards = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.notebook_cards, ids[i])
		m.removednotebook_cards[ids[i]] = struct{}{}
	}
}

// RemovedNotebookCards returns the removed IDs of the "notebook_cards" edge to the NotebookCard entity.
func (m *CardMutation) RemovedNotebookCardsIDs() (ids []string) {
	for id := range m.removednotebook_cards {
		ids = append(ids, id)
	}
	return
}

// NotebookCardsIDs returns the "notebook_cards" edge IDs in the mutation.
func (m *CardMutation) NotebookCardsIDs() (ids []string) {
	for id := range m.notebook_cards {
		ids = append(ids, id)
	}
	return
}

// ResetNotebookCards resets all changes to the "notebook_cards" edge.
func (m *CardMutation) ResetNotebookCards() {
	m.notebook_cards = nil
	m.clearednotebook_cards = false
	m.removednotebook_cards = nil
}

// Where appends a list predicates to the CardMutation builder.
func (m *CardMutation) Where(ps ...predicate.Card) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CardMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CardMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Card, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CardMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CardMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Card).
func (m *CardMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CardMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.hint != nil {
		fields = append(fields, card.FieldHint)
	}
	if m.content != nil {
		fields = append(fields, card.FieldContent)
	}
	if m.created_at != nil {
		fields = append(fields, card.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, card.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CardMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case card.FieldHint:
		return m.Hint()
	case card.FieldContent:
		return m.Content()
	case card.FieldCreatedAt:
		return m.CreatedAt()
	case card.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CardMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case card.FieldHint:
		return m.OldHint(ctx)
	case card.FieldContent:
		return m.OldContent(ctx)
	case card.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case card.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Card field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CardMutation) SetField(name string, value ent.Value) error {
	switch name {
	case card.FieldHint:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHint(v)
		return nil
	case card.FieldContent:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContent(v)
		return nil
	case card.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case card.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Card field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CardMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CardMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CardMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Card numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CardMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(card.FieldHint) {
		fields = append(fields, card.FieldHint)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CardMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CardMutation) ClearField(name string) error {
	switch name {
	case card.FieldHint:
		m.ClearHint()
		return nil
	}
	return fmt.Errorf("unknown Card nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CardMutation) ResetField(name string) error {
	switch name {
	case card.FieldHint:
		m.ResetHint()
		return nil
	case card.FieldContent:
		m.ResetContent()
		return nil
	case card.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case card.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Card field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CardMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.creator != nil {
		edges = append(edges, card.EdgeCreator)
	}
	if m.decks != nil {
		edges = append(edges, card.EdgeDecks)
	}
	if m.notebook_cards != nil {
		edges = append(edges, card.EdgeNotebookCards)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CardMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case card.EdgeCreator:
		if id := m.creator; id != nil {
			return []ent.Value{*id}
		}
	case card.EdgeDecks:
		ids := make([]ent.Value, 0, len(m.decks))
		for id := range m.decks {
			ids = append(ids, id)
		}
		return ids
	case card.EdgeNotebookCards:
		ids := make([]ent.Value, 0, len(m.notebook_cards))
		for id := range m.notebook_cards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CardMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removeddecks != nil {
		edges = append(edges, card.EdgeDecks)
	}
	if m.removednotebook_cards != nil {
		edges = append(edges, card.EdgeNotebookCards)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CardMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case card.EdgeDecks:
		ids := make([]ent.Value, 0, len(m.removeddecks))
		for id := range m.removeddecks {
			ids = append(ids, id)
		}
		return ids
	case card.EdgeNotebookCards:
		ids := make([]ent.Value, 0, len(m.removednotebook_cards))
		for id := range m.removednotebook_cards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CardMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedcreator {
		edges = append(edges, card.EdgeCreator)
	}
	if m.cleareddecks {
		edges = append(edges, card.EdgeDecks)
	}
	if m.clearednotebook_cards {
		edges = append(edges, card.EdgeNotebookCards)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CardMutation) EdgeCleared(name string) bool {
	switch name {
	case card.EdgeCreator:
		return m.clearedcreator
	case card.EdgeDecks:
		return m.cleareddecks
	case card.EdgeNotebookCards:
		return m.clearednotebook_cards
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CardMutation) ClearEdge(name string) error {
	switch name {
	case card.EdgeCreator:
		m.ClearCreator()
		return nil
	}
	return fmt.Errorf("unknown Card unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CardMutation) ResetEdge(name string) error {
	switch name {
	case card.EdgeCreator:
		m.ResetCreator()
		return nil
	case card.EdgeDecks:
		m.ResetDecks()
		return nil
	case card.EdgeNotebookCards:
		m.ResetNotebookCards()
		return nil
	}
	return fmt.Errorf("unknown Card edge %s", name)
}

// DeckMutation represents an operation that mutates the Deck nodes in the graph.
type DeckMutation struct {
	config
	op                    Op
	typ                   string
	id                    *string
	name                  *string
	created_at            *time.Time
	updated_at            *time.Time
	clearedFields         map[string]struct{}
	creator               *string
	clearedcreator        bool
	cards                 map[string]struct{}
	removedcards          map[string]struct{}
	clearedcards          bool
	notebook_cards        map[string]struct{}
	removednotebook_cards map[string]struct{}
	clearednotebook_cards bool
	done                  bool
	oldValue              func(context.Context) (*Deck, error)
	predicates            []predicate.Deck
}

var _ ent.Mutation = (*DeckMutation)(nil)

// deckOption allows management of the mutation configuration using functional options.
type deckOption func(*DeckMutation)

// newDeckMutation creates new mutation for the Deck entity.
func newDeckMutation(c config, op Op, opts ...deckOption) *DeckMutation {
	m := &DeckMutation{
		config:        c,
		op:            op,
		typ:           TypeDeck,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDeckID sets the ID field of the mutation.
func withDeckID(id string) deckOption {
	return func(m *DeckMutation) {
		var (
			err   error
			once  sync.Once
			value *Deck
		)
		m.oldValue = func(ctx context.Context) (*Deck, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Deck.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDeck sets the old Deck of the mutation.
func withDeck(node *Deck) deckOption {
	return func(m *DeckMutation) {
		m.oldValue = func(context.Context) (*Deck, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DeckMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DeckMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Deck entities.
func (m *DeckMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DeckMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DeckMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Deck.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *DeckMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *DeckMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Deck entity.
// If the Deck object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeckMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *DeckMutation) ResetName() {
	m.name = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *DeckMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DeckMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Deck entity.
// If the Deck object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeckMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DeckMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *DeckMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *DeckMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Deck entity.
// If the Deck object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DeckMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *DeckMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetCreatorID sets the "creator" edge to the User entity by id.
func (m *DeckMutation) SetCreatorID(id string) {
	m.creator = &id
}

// ClearCreator clears the "creator" edge to the User entity.
func (m *DeckMutation) ClearCreator() {
	m.clearedcreator = true
}

// CreatorCleared reports if the "creator" edge to the User entity was cleared.
func (m *DeckMutation) CreatorCleared() bool {
	return m.clearedcreator
}

// CreatorID returns the "creator" edge ID in the mutation.
func (m *DeckMutation) CreatorID() (id string, exists bool) {
	if m.creator != nil {
		return *m.creator, true
	}
	return
}

// CreatorIDs returns the "creator" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CreatorID instead. It exists only for internal usage by the builders.
func (m *DeckMutation) CreatorIDs() (ids []string) {
	if id := m.creator; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCreator resets all changes to the "creator" edge.
func (m *DeckMutation) ResetCreator() {
	m.creator = nil
	m.clearedcreator = false
}

// AddCardIDs adds the "cards" edge to the Card entity by ids.
func (m *DeckMutation) AddCardIDs(ids ...string) {
	if m.cards == nil {
		m.cards = make(map[string]struct{})
	}
	for i := range ids {
		m.cards[ids[i]] = struct{}{}
	}
}

// ClearCards clears the "cards" edge to the Card entity.
func (m *DeckMutation) ClearCards() {
	m.clearedcards = true
}

// CardsCleared reports if the "cards" edge to the Card entity was cleared.
func (m *DeckMutation) CardsCleared() bool {
	return m.clearedcards
}

// RemoveCardIDs removes the "cards" edge to the Card entity by IDs.
func (m *DeckMutation) RemoveCardIDs(ids ...string) {
	if m.removedcards == nil {
		m.removedcards = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.cards, ids[i])
		m.removedcards[ids[i]] = struct{}{}
	}
}

// RemovedCards returns the removed IDs of the "cards" edge to the Card entity.
func (m *DeckMutation) RemovedCardsIDs() (ids []string) {
	for id := range m.removedcards {
		ids = append(ids, id)
	}
	return
}

// CardsIDs returns the "cards" edge IDs in the mutation.
func (m *DeckMutation) CardsIDs() (ids []string) {
	for id := range m.cards {
		ids = append(ids, id)
	}
	return
}

// ResetCards resets all changes to the "cards" edge.
func (m *DeckMutation) ResetCards() {
	m.cards = nil
	m.clearedcards = false
	m.removedcards = nil
}

// AddNotebookCardIDs adds the "notebook_cards" edge to the NotebookCard entity by ids.
func (m *DeckMutation) AddNotebookCardIDs(ids ...string) {
	if m.notebook_cards == nil {
		m.notebook_cards = make(map[string]struct{})
	}
	for i := range ids {
		m.notebook_cards[ids[i]] = struct{}{}
	}
}

// ClearNotebookCards clears the "notebook_cards" edge to the NotebookCard entity.
func (m *DeckMutation) ClearNotebookCards() {
	m.clearednotebook_cards = true
}

// NotebookCardsCleared reports if the "notebook_cards" edge to the NotebookCard entity was cleared.
func (m *DeckMutation) NotebookCardsCleared() bool {
	return m.clearednotebook_cards
}

// RemoveNotebookCardIDs removes the "notebook_cards" edge to the NotebookCard entity by IDs.
func (m *DeckMutation) RemoveNotebookCardIDs(ids ...string) {
	if m.removednotebook_cards == nil {
		m.removednotebook_cards = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.notebook_cards, ids[i])
		m.removednotebook_cards[ids[i]] = struct{}{}
	}
}

// RemovedNotebookCards returns the removed IDs of the "notebook_cards" edge to the NotebookCard entity.
func (m *DeckMutation) RemovedNotebookCardsIDs() (ids []string) {
	for id := range m.removednotebook_cards {
		ids = append(ids, id)
	}
	return
}

// NotebookCardsIDs returns the "notebook_cards" edge IDs in the mutation.
func (m *DeckMutation) NotebookCardsIDs() (ids []string) {
	for id := range m.notebook_cards {
		ids = append(ids, id)
	}
	return
}

// ResetNotebookCards resets all changes to the "notebook_cards" edge.
func (m *DeckMutation) ResetNotebookCards() {
	m.notebook_cards = nil
	m.clearednotebook_cards = false
	m.removednotebook_cards = nil
}

// Where appends a list predicates to the DeckMutation builder.
func (m *DeckMutation) Where(ps ...predicate.Deck) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DeckMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DeckMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Deck, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DeckMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DeckMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Deck).
func (m *DeckMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DeckMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, deck.FieldName)
	}
	if m.created_at != nil {
		fields = append(fields, deck.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, deck.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DeckMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case deck.FieldName:
		return m.Name()
	case deck.FieldCreatedAt:
		return m.CreatedAt()
	case deck.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DeckMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case deck.FieldName:
		return m.OldName(ctx)
	case deck.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case deck.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Deck field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeckMutation) SetField(name string, value ent.Value) error {
	switch name {
	case deck.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case deck.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case deck.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Deck field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DeckMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DeckMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DeckMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Deck numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DeckMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DeckMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DeckMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Deck nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DeckMutation) ResetField(name string) error {
	switch name {
	case deck.FieldName:
		m.ResetName()
		return nil
	case deck.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case deck.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Deck field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DeckMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.creator != nil {
		edges = append(edges, deck.EdgeCreator)
	}
	if m.cards != nil {
		edges = append(edges, deck.EdgeCards)
	}
	if m.notebook_cards != nil {
		edges = append(edges, deck.EdgeNotebookCards)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DeckMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case deck.EdgeCreator:
		if id := m.creator; id != nil {
			return []ent.Value{*id}
		}
	case deck.EdgeCards:
		ids := make([]ent.Value, 0, len(m.cards))
		for id := range m.cards {
			ids = append(ids, id)
		}
		return ids
	case deck.EdgeNotebookCards:
		ids := make([]ent.Value, 0, len(m.notebook_cards))
		for id := range m.notebook_cards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DeckMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedcards != nil {
		edges = append(edges, deck.EdgeCards)
	}
	if m.removednotebook_cards != nil {
		edges = append(edges, deck.EdgeNotebookCards)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DeckMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case deck.EdgeCards:
		ids := make([]ent.Value, 0, len(m.removedcards))
		for id := range m.removedcards {
			ids = append(ids, id)
		}
		return ids
	case deck.EdgeNotebookCards:
		ids := make([]ent.Value, 0, len(m.removednotebook_cards))
		for id := range m.removednotebook_cards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DeckMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedcreator {
		edges = append(edges, deck.EdgeCreator)
	}
	if m.clearedcards {
		edges = append(edges, deck.EdgeCards)
	}
	if m.clearednotebook_cards {
		edges = append(edges, deck.EdgeNotebookCards)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DeckMutation) EdgeCleared(name string) bool {
	switch name {
	case deck.EdgeCreator:
		return m.clearedcreator
	case deck.EdgeCards:
		return m.clearedcards
	case deck.EdgeNotebookCards:
		return m.clearednotebook_cards
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DeckMutation) ClearEdge(name string) error {
	switch name {
	case deck.EdgeCreator:
		m.ClearCreator()
		return nil
	}
	return fmt.Errorf("unknown Deck unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DeckMutation) ResetEdge(name string) error {
	switch name {
	case deck.EdgeCreator:
		m.ResetCreator()
		return nil
	case deck.EdgeCards:
		m.ResetCards()
		return nil
	case deck.EdgeNotebookCards:
		m.ResetNotebookCards()
		return nil
	}
	return fmt.Errorf("unknown Deck edge %s", name)
}

// NotebookMutation represents an operation that mutates the Notebook nodes in the graph.
type NotebookMutation struct {
	config
	op                    Op
	typ                   string
	id                    *string
	name                  *string
	created_at            *time.Time
	updated_at            *time.Time
	clearedFields         map[string]struct{}
	creator               *string
	clearedcreator        bool
	notebook_cards        map[string]struct{}
	removednotebook_cards map[string]struct{}
	clearednotebook_cards bool
	done                  bool
	oldValue              func(context.Context) (*Notebook, error)
	predicates            []predicate.Notebook
}

var _ ent.Mutation = (*NotebookMutation)(nil)

// notebookOption allows management of the mutation configuration using functional options.
type notebookOption func(*NotebookMutation)

// newNotebookMutation creates new mutation for the Notebook entity.
func newNotebookMutation(c config, op Op, opts ...notebookOption) *NotebookMutation {
	m := &NotebookMutation{
		config:        c,
		op:            op,
		typ:           TypeNotebook,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotebookID sets the ID field of the mutation.
func withNotebookID(id string) notebookOption {
	return func(m *NotebookMutation) {
		var (
			err   error
			once  sync.Once
			value *Notebook
		)
		m.oldValue = func(ctx context.Context) (*Notebook, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Notebook.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotebook sets the old Notebook of the mutation.
func withNotebook(node *Notebook) notebookOption {
	return func(m *NotebookMutation) {
		m.oldValue = func(context.Context) (*Notebook, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotebookMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotebookMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Notebook entities.
func (m *NotebookMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotebookMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotebookMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Notebook.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *NotebookMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *NotebookMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *NotebookMutation) ResetName() {
	m.name = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *NotebookMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NotebookMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NotebookMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *NotebookMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *NotebookMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Notebook entity.
// If the Notebook object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *NotebookMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetCreatorID sets the "creator" edge to the User entity by id.
func (m *NotebookMutation) SetCreatorID(id string) {
	m.creator = &id
}

// ClearCreator clears the "creator" edge to the User entity.
func (m *NotebookMutation) ClearCreator() {
	m.clearedcreator = true
}

// CreatorCleared reports if the "creator" edge to the User entity was cleared.
func (m *NotebookMutation) CreatorCleared() bool {
	return m.clearedcreator
}

// CreatorID returns the "creator" edge ID in the mutation.
func (m *NotebookMutation) CreatorID() (id string, exists bool) {
	if m.creator != nil {
		return *m.creator, true
	}
	return
}

// CreatorIDs returns the "creator" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CreatorID instead. It exists only for internal usage by the builders.
func (m *NotebookMutation) CreatorIDs() (ids []string) {
	if id := m.creator; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCreator resets all changes to the "creator" edge.
func (m *NotebookMutation) ResetCreator() {
	m.creator = nil
	m.clearedcreator = false
}

// AddNotebookCardIDs adds the "notebook_cards" edge to the NotebookCard entity by ids.
func (m *NotebookMutation) AddNotebookCardIDs(ids ...string) {
	if m.notebook_cards == nil {
		m.notebook_cards = make(map[string]struct{})
	}
	for i := range ids {
		m.notebook_cards[ids[i]] = struct{}{}
	}
}

// ClearNotebookCards clears the "notebook_cards" edge to the NotebookCard entity.
func (m *NotebookMutation) ClearNotebookCards() {
	m.clearednotebook_cards = true
}

// NotebookCardsCleared reports if the "notebook_cards" edge to the NotebookCard entity was cleared.
func (m *NotebookMutation) NotebookCardsCleared() bool {
	return m.clearednotebook_cards
}

// RemoveNotebookCardIDs removes the "notebook_cards" edge to the NotebookCard entity by IDs.
func (m *NotebookMutation) RemoveNotebookCardIDs(ids ...string) {
	if m.removednotebook_cards == nil {
		m.removednotebook_cards = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.notebook_cards, ids[i])
		m.removednotebook_cards[ids[i]] = struct{}{}
	}
}

// RemovedNotebookCards returns the removed IDs of the "notebook_cards" edge to the NotebookCard entity.
func (m *NotebookMutation) RemovedNotebookCardsIDs() (ids []string) {
	for id := range m.removednotebook_cards {
		ids = append(ids, id)
	}
	return
}

// NotebookCardsIDs returns the "notebook_cards" edge IDs in the mutation.
func (m *NotebookMutation) NotebookCardsIDs() (ids []string) {
	for id := range m.notebook_cards {
		ids = append(ids, id)
	}
	return
}

// ResetNotebookCards resets all changes to the "notebook_cards" edge.
func (m *NotebookMutation) ResetNotebookCards() {
	m.notebook_cards = nil
	m.clearednotebook_cards = false
	m.removednotebook_cards = nil
}

// Where appends a list predicates to the NotebookMutation builder.
func (m *NotebookMutation) Where(ps ...predicate.Notebook) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotebookMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotebookMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Notebook, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotebookMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotebookMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Notebook).
func (m *NotebookMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotebookMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, notebook.FieldName)
	}
	if m.created_at != nil {
		fields = append(fields, notebook.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, notebook.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotebookMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notebook.FieldName:
		return m.Name()
	case notebook.FieldCreatedAt:
		return m.CreatedAt()
	case notebook.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotebookMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notebook.FieldName:
		return m.OldName(ctx)
	case notebook.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case notebook.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Notebook field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notebook.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case notebook.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case notebook.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Notebook field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotebookMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotebookMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Notebook numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotebookMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotebookMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotebookMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Notebook nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotebookMutation) ResetField(name string) error {
	switch name {
	case notebook.FieldName:
		m.ResetName()
		return nil
	case notebook.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case notebook.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Notebook field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotebookMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.creator != nil {
		edges = append(edges, notebook.EdgeCreator)
	}
	if m.notebook_cards != nil {
		edges = append(edges, notebook.EdgeNotebookCards)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotebookMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case notebook.EdgeCreator:
		if id := m.creator; id != nil {
			return []ent.Value{*id}
		}
	case notebook.EdgeNotebookCards:
		ids := make([]ent.Value, 0, len(m.notebook_cards))
		for id := range m.notebook_cards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotebookMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removednotebook_cards != nil {
		edges = append(edges, notebook.EdgeNotebookCards)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotebookMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case notebook.EdgeNotebookCards:
		ids := make([]ent.Value, 0, len(m.removednotebook_cards))
		for id := range m.removednotebook_cards {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotebookMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedcreator {
		edges = append(edges, notebook.EdgeCreator)
	}
	if m.clearednotebook_cards {
		edges = append(edges, notebook.EdgeNotebookCards)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotebookMutation) EdgeCleared(name string) bool {
	switch name {
	case notebook.EdgeCreator:
		return m.clearedcreator
	case notebook.EdgeNotebookCards:
		return m.clearednotebook_cards
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotebookMutation) ClearEdge(name string) error {
	switch name {
	case notebook.EdgeCreator:
		m.ClearCreator()
		return nil
	}
	return fmt.Errorf("unknown Notebook unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotebookMutation) ResetEdge(name string) error {
	switch name {
	case notebook.EdgeCreator:
		m.ResetCreator()
		return nil
	case notebook.EdgeNotebookCards:
		m.ResetNotebookCards()
		return nil
	}
	return fmt.Errorf("unknown Notebook edge %s", name)
}

// NotebookCardMutation represents an operation that mutates the NotebookCard nodes in the graph.
type NotebookCardMutation struct {
	config
	op              Op
	typ             string
	id              *string
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	notebook        *string
	clearednotebook bool
	card            *string
	clearedcard     bool
	deck            *string
	cleareddeck     bool
	done            bool
	oldValue        func(context.Context) (*NotebookCard, error)
	predicates      []predicate.NotebookCard
}

var _ ent.Mutation = (*NotebookCardMutation)(nil)

// notebookcardOption allows management of the mutation configuration using functional options.
type notebookcardOption func(*NotebookCardMutation)

// newNotebookCardMutation creates new mutation for the NotebookCard entity.
func newNotebookCardMutation(c config, op Op, opts ...notebookcardOption) *NotebookCardMutation {
	m := &NotebookCardMutation{
		config:        c,
		op:            op,
		typ:           TypeNotebookCard,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withNotebookCardID sets the ID field of the mutation.
func withNotebookCardID(id string) notebookcardOption {
	return func(m *NotebookCardMutation) {
		var (
			err   error
			once  sync.Once
			value *NotebookCard
		)
		m.oldValue = func(ctx context.Context) (*NotebookCard, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().NotebookCard.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withNotebookCard sets the old NotebookCard of the mutation.
func withNotebookCard(node *NotebookCard) notebookcardOption {
	return func(m *NotebookCardMutation) {
		m.oldValue = func(context.Context) (*NotebookCard, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m NotebookCardMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m NotebookCardMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of NotebookCard entities.
func (m *NotebookCardMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *NotebookCardMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *NotebookCardMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().NotebookCard.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *NotebookCardMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *NotebookCardMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the NotebookCard entity.
// If the NotebookCard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookCardMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *NotebookCardMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *NotebookCardMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *NotebookCardMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the NotebookCard entity.
// If the NotebookCard object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *NotebookCardMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *NotebookCardMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetNotebookID sets the "notebook" edge to the Notebook entity by id.
func (m *NotebookCardMutation) SetNotebookID(id string) {
	m.notebook = &id
}

// ClearNotebook clears the "notebook" edge to the Notebook entity.
func (m *NotebookCardMutation) ClearNotebook() {
	m.clearednotebook = true
}

// NotebookCleared reports if the "notebook" edge to the Notebook entity was cleared.
func (m *NotebookCardMutation) NotebookCleared() bool {
	return m.clearednotebook
}

// NotebookID returns the "notebook" edge ID in the mutation.
func (m *NotebookCardMutation) NotebookID() (id string, exists bool) {
	if m.notebook != nil {
		return *m.notebook, true
	}
	return
}

// NotebookIDs returns the "notebook" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// NotebookID instead. It exists only for internal usage by the builders.
func (m *NotebookCardMutation) NotebookIDs() (ids []string) {
	if id := m.notebook; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetNotebook resets all changes to the "notebook" edge.
func (m *NotebookCardMutation) ResetNotebook() {
	m.notebook = nil
	m.clearednotebook = false
}

// SetCardID sets the "card" edge to the Card entity by id.
func (m *NotebookCardMutation) SetCardID(id string) {
	m.card = &id
}

// ClearCard clears the "card" edge to the Card entity.
func (m *NotebookCardMutation) ClearCard() {
	m.clearedcard = true
}

// CardCleared reports if the "card" edge to the Card entity was cleared.
func (m *NotebookCardMutation) CardCleared() bool {
	return m.clearedcard
}

// CardID returns the "card" edge ID in the mutation.
func (m *NotebookCardMutation) CardID() (id string, exists bool) {
	if m.card != nil {
		return *m.card, true
	}
	return
}

// CardIDs returns the "card" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// CardID instead. It exists only for internal usage by the builders.
func (m *NotebookCardMutation) CardIDs() (ids []string) {
	if id := m.card; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetCard resets all changes to the "card" edge.
func (m *NotebookCardMutation) ResetCard() {
	m.card = nil
	m.clearedcard = false
}

// SetDeckID sets the "deck" edge to the Deck entity by id.
func (m *NotebookCardMutation) SetDeckID(id string) {
	m.deck = &id
}

// ClearDeck clears the "deck" edge to the Deck entity.
func (m *NotebookCardMutation) ClearDeck() {
	m.cleareddeck = true
}

// DeckCleared reports if the "deck" edge to the Deck entity was cleared.
func (m *NotebookCardMutation) DeckCleared() bool {
	return m.cleareddeck
}

// DeckID returns the "deck" edge ID in the mutation.
func (m *NotebookCardMutation) DeckID() (id string, exists bool) {
	if m.deck != nil {
		return *m.deck, true
	}
	return
}

// DeckIDs returns the "deck" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// DeckID instead. It exists only for internal usage by the builders.
func (m *NotebookCardMutation) DeckIDs() (ids []string) {
	if id := m.deck; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDeck resets all changes to the "deck" edge.
func (m *NotebookCardMutation) ResetDeck() {
	m.deck = nil
	m.cleareddeck = false
}

// Where appends a list predicates to the NotebookCardMutation builder.
func (m *NotebookCardMutation) Where(ps ...predicate.NotebookCard) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the NotebookCardMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *NotebookCardMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.NotebookCard, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *NotebookCardMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *NotebookCardMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (NotebookCard).
func (m *NotebookCardMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *NotebookCardMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.created_at != nil {
		fields = append(fields, notebookcard.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, notebookcard.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *NotebookCardMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case notebookcard.FieldCreatedAt:
		return m.CreatedAt()
	case notebookcard.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *NotebookCardMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case notebookcard.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case notebookcard.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown NotebookCard field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookCardMutation) SetField(name string, value ent.Value) error {
	switch name {
	case notebookcard.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case notebookcard.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown NotebookCard field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *NotebookCardMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *NotebookCardMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *NotebookCardMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown NotebookCard numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *NotebookCardMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *NotebookCardMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *NotebookCardMutation) ClearField(name string) error {
	return fmt.Errorf("unknown NotebookCard nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *NotebookCardMutation) ResetField(name string) error {
	switch name {
	case notebookcard.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case notebookcard.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown NotebookCard field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *NotebookCardMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.notebook != nil {
		edges = append(edges, notebookcard.EdgeNotebook)
	}
	if m.card != nil {
		edges = append(edges, notebookcard.EdgeCard)
	}
	if m.deck != nil {
		edges = append(edges, notebookcard.EdgeDeck)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *NotebookCardMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case notebookcard.EdgeNotebook:
		if id := m.notebook; id != nil {
			return []ent.Value{*id}
		}
	case notebookcard.EdgeCard:
		if id := m.card; id != nil {
			return []ent.Value{*id}
		}
	case notebookcard.EdgeDeck:
		if id := m.deck; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *NotebookCardMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *NotebookCardMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *NotebookCardMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearednotebook {
		edges = append(edges, notebookcard.EdgeNotebook)
	}
	if m.clearedcard {
		edges = append(edges, notebookcard.EdgeCard)
	}
	if m.cleareddeck {
		edges = append(edges, notebookcard.EdgeDeck)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *NotebookCardMutation) EdgeCleared(name string) bool {
	switch name {
	case notebookcard.EdgeNotebook:
		return m.clearednotebook
	case notebookcard.EdgeCard:
		return m.clearedcard
	case notebookcard.EdgeDeck:
		return m.cleareddeck
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *NotebookCardMutation) ClearEdge(name string) error {
	switch name {
	case notebookcard.EdgeNotebook:
		m.ClearNotebook()
		return nil
	case notebookcard.EdgeCard:
		m.ClearCard()
		return nil
	case notebookcard.EdgeDeck:
		m.ClearDeck()
		return nil
	}
	return fmt.Errorf("unknown NotebookCard unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *NotebookCardMutation) ResetEdge(name string) error {
	switch name {
	case notebookcard.EdgeNotebook:
		m.ResetNotebook()
		return nil
	case notebookcard.EdgeCard:
		m.ResetCard()
		return nil
	case notebookcard.EdgeDeck:
		m.ResetDeck()
		return nil
	}
	return fmt.Errorf("unknown NotebookCard edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op               Op
	typ              string
	id               *string
	nickname         *string
	provider_id      *string
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	cards            map[string]struct{}
	removedcards     map[string]struct{}
	clearedcards     bool
	decks            map[string]struct{}
	removeddecks     map[string]struct{}
	cleareddecks     bool
	notebooks        map[string]struct{}
	removednotebooks map[string]struct{}
	clearednotebooks bool
	done             bool
	oldValue         func(context.Context) (*User, error)
	predicates       []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id string) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNickname sets the "nickname" field.
func (m *UserMutation) SetNickname(s string) {
	m.nickname = &s
}

// Nickname returns the value of the "nickname" field in the mutation.
func (m *UserMutation) Nickname() (r string, exists bool) {
	v := m.nickname
	if v == nil {
		return
	}
	return *v, true
}

// OldNickname returns the old "nickname" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldNickname(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNickname is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNickname requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNickname: %w", err)
	}
	return oldValue.Nickname, nil
}

// ResetNickname resets all changes to the "nickname" field.
func (m *UserMutation) ResetNickname() {
	m.nickname = nil
}

// SetProviderID sets the "provider_id" field.
func (m *UserMutation) SetProviderID(s string) {
	m.provider_id = &s
}

// ProviderID returns the value of the "provider_id" field in the mutation.
func (m *UserMutation) ProviderID() (r string, exists bool) {
	v := m.provider_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderID returns the old "provider_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldProviderID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderID: %w", err)
	}
	return oldValue.ProviderID, nil
}

// ResetProviderID resets all changes to the "provider_id" field.
func (m *UserMutation) ResetProviderID() {
	m.provider_id = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddCardIDs adds the "cards" edge to the Card entity by ids.
func (m *UserMutation) AddCardIDs(ids ...string) {
	if m.cards == nil {
		m.cards = make(map[string]struct{})
	}
	for i := range ids {
		m.cards[ids[i]] = struct{}{}
	}
}

// ClearCards clears the "cards" edge to the Card entity.
func (m *UserMutation) ClearCards() {
	m.clearedcards = true
}

// CardsCleared reports if the "cards" edge to the Card entity was cleared.
func (m *UserMutation) CardsCleared() bool {
	return m.clearedcards
}

// RemoveCardIDs removes the "cards" edge to the Card entity by IDs.
func (m *UserMutation) RemoveCardIDs(ids ...string) {
	if m.removedcards == nil {
		m.removedcards = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.cards, ids[i])
		m.removedcards[ids[i]] = struct{}{}
	}
}

// RemovedCards returns the removed IDs of the "cards" edge to the Card entity.
func (m *UserMutation) RemovedCardsIDs() (ids []string) {
	for id := range m.removedcards {
		ids = append(ids, id)
	}
	return
}

// CardsIDs returns the "cards" edge IDs in the mutation.
func (m *UserMutation) CardsIDs() (ids []string) {
	for id := range m.cards {
		ids = append(ids, id)
	}
	return
}

// ResetCards resets all changes to the "cards" edge.
func (m *UserMutation) ResetCards() {
	m.cards = nil
	m.clearedcards = false
	m.removedcards = nil
}

// AddDeckIDs adds the "decks" edge to the Deck entity by ids.
func (m *UserMutation) AddDeckIDs(ids ...string) {
	if m.decks == nil {
		m.decks = make(map[string]struct{})
	}
	for i := range ids {
		m.decks[ids[i]] = struct{}{}
	}
}

// ClearDecks clears the "decks" edge to the Deck entity.
func (m *UserMutation) ClearDecks() {
	m.cleareddecks = true
}

// DecksCleared reports if the "decks" edge to the Deck entity was cleared.
func (m *UserMutation) DecksCleared() bool {
	return m.cleareddecks
}

// RemoveDeckIDs removes the "decks" edge to the Deck entity by IDs.
func (m *UserMutation) RemoveDeckIDs(ids ...string) {
	if m.removeddecks == nil {
		m.removeddecks = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.decks, ids[i])
		m.removeddecks[ids[i]] = struct{}{}
	}
}

// RemovedDecks returns the removed IDs of the "decks" edge to the Deck entity.
func (m *UserMutation) RemovedDecksIDs() (ids []string) {
	for id := range m.removeddecks {
		ids = append(ids, id)
	}
	return
}

// DecksIDs returns the "decks" edge IDs in the mutation.
func (m *UserMutation) DecksIDs() (ids []string) {
	for id := range m.decks {
		ids = append(ids, id)
	}
	return
}

// ResetDecks resets all changes to the "decks" edge.
func (m *UserMutation) ResetDecks() {
	m.decks = nil
	m.cleareddecks = false
	m.removeddecks = nil
}

// AddNotebookIDs adds the "notebooks" edge to the Notebook entity by ids.
func (m *UserMutation) AddNotebookIDs(ids ...string) {
	if m.notebooks == nil {
		m.notebooks = make(map[string]struct{})
	}
	for i := range ids {
		m.notebooks[ids[i]] = struct{}{}
	}
}

// ClearNotebooks clears the "notebooks" edge to the Notebook entity.
func (m *UserMutation) ClearNotebooks() {
	m.clearednotebooks = true
}

// NotebooksCleared reports if the "notebooks" edge to the Notebook entity was cleared.
func (m *UserMutation) NotebooksCleared() bool {
	return m.clearednotebooks
}

// RemoveNotebookIDs removes the "notebooks" edge to the Notebook entity by IDs.
func (m *UserMutation) RemoveNotebookIDs(ids ...string) {
	if m.removednotebooks == nil {
		m.removednotebooks = make(map[string]struct{})
	}
	for i := range ids {
		delete(m.notebooks, ids[i])
		m.removednotebooks[ids[i]] = struct{}{}
	}
}

// RemovedNotebooks returns the removed IDs of the "notebooks" edge to the Notebook entity.
func (m *UserMutation) RemovedNotebooksIDs() (ids []string) {
	for id := range m.removednotebooks {
		ids = append(ids, id)
	}
	return
}

// NotebooksIDs returns the "notebooks" edge IDs in the mutation.
func (m *UserMutation) NotebooksIDs() (ids []string) {
	for id := range m.notebooks {
		ids = append(ids, id)
	}
	return
}

// ResetNotebooks resets all changes to the "notebooks" edge.
func (m *UserMutation) ResetNotebooks() {
	m.notebooks = nil
	m.clearednotebooks = false
	m.removednotebooks = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.nickname != nil {
		fields = append(fields, user.FieldNickname)
	}
	if m.provider_id != nil {
		fields = append(fields, user.FieldProviderID)
	}
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldNickname:
		return m.Nickname()
	case user.FieldProviderID:
		return m.ProviderID()
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldNickname:
		return m.OldNickname(ctx)
	case user.FieldProviderID:
		return m.OldProviderID(ctx)
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldNickname:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNickname(v)
		return nil
	case user.FieldProviderID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderID(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldNickname:
		m.ResetNickname()
		return nil
	case user.FieldProviderID:
		m.ResetProviderID()
		return nil
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.cards != nil {
		edges = append(edges, user.EdgeCards)
	}
	if m.decks != nil {
		edges = append(edges, user.EdgeDecks)
	}
	if m.notebooks != nil {
		edges = append(edges, user.EdgeNotebooks)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCards:
		ids := make([]ent.Value, 0, len(m.cards))
		for id := range m.cards {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeDecks:
		ids := make([]ent.Value, 0, len(m.decks))
		for id := range m.decks {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeNotebooks:
		ids := make([]ent.Value, 0, len(m.notebooks))
		for id := range m.notebooks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedcards != nil {
		edges = append(edges, user.EdgeCards)
	}
	if m.removeddecks != nil {
		edges = append(edges, user.EdgeDecks)
	}
	if m.removednotebooks != nil {
		edges = append(edges, user.EdgeNotebooks)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeCards:
		ids := make([]ent.Value, 0, len(m.removedcards))
		for id := range m.removedcards {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeDecks:
		ids := make([]ent.Value, 0, len(m.removeddecks))
		for id := range m.removeddecks {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeNotebooks:
		ids := make([]ent.Value, 0, len(m.removednotebooks))
		for id := range m.removednotebooks {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedcards {
		edges = append(edges, user.EdgeCards)
	}
	if m.cleareddecks {
		edges = append(edges, user.EdgeDecks)
	}
	if m.clearednotebooks {
		edges = append(edges, user.EdgeNotebooks)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeCards:
		return m.clearedcards
	case user.EdgeDecks:
		return m.cleareddecks
	case user.EdgeNotebooks:
		return m.clearednotebooks
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeCards:
		m.ResetCards()
		return nil
	case user.EdgeDecks:
		m.ResetDecks()
		return nil
	case user.EdgeNotebooks:
		m.ResetNotebooks()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
