// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mandacode-labs/dodream/ent/notebook"
	"github.com/mandacode-labs/dodream/ent/user"
)

// Notebook is the model entity for the Notebook schema.
type Notebook struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotebookQuery when eager-loading is set.
	Edges          NotebookEdges `json:"edges"`
	user_notebooks *string
	selectValues   sql.SelectValues
}

// NotebookEdges holds the relations/edges for other nodes in the graph.
type NotebookEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// NotebookCards holds the value of the notebook_cards edge.
	NotebookCards []*NotebookCard `json:"notebook_cards,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotebookEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// NotebookCardsOrErr returns the NotebookCards value or an error if the edge
// was not loaded in eager-loading.
func (e NotebookEdges) NotebookCardsOrErr() ([]*NotebookCard, error) {
	if e.loadedTypes[1] {
		return e.NotebookCards, nil
	}
	return nil, &NotLoadedError{edge: "notebook_cards"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notebook) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notebook.FieldID, notebook.FieldName:
			values[i] = new(sql.NullString)
		case notebook.FieldCreatedAt, notebook.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case notebook.ForeignKeys[0]: // user_notebooks
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notebook fields.
func (_m *Notebook) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notebook.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case notebook.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case notebook.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case notebook.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case notebook.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_notebooks", values[i])
			} else if value.Valid {
				_m.user_notebooks = new(string)
				*_m.user_notebooks = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Notebook.
// This includes values selected through modifiers, order, etc.
func (_m *Notebook) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Notebook entity.
func (_m *Notebook) QueryCreator() *UserQuery {
	return NewNotebookClient(_m.config).QueryCreator(_m)
}

// QueryNotebookCards queries the "notebook_cards" edge of the Notebook entity.
func (_m *Notebook) QueryNotebookCards() *NotebookCardQuery {
	return NewNotebookClient(_m.config).QueryNotebookCards(_m)
}

// Update returns a builder for updating this Notebook.
// Note that you need to call Notebook.Unwrap() before calling this method if this Notebook
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Notebook) Update() *NotebookUpdateOne {
	return NewNotebookClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Notebook entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Notebook) Unwrap() *Notebook {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notebook is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Notebook) String() string {
	var builder strings.Builder
	builder.WriteString("Notebook(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Notebooks is a parsable slice of Notebook.
type Notebooks []*Notebook
