// Code generated by ent, DO NOT EDIT.

package state

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the state type in the database.
	Label = "state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNextReviewAt holds the string denoting the next_review_at field in the database.
	FieldNextReviewAt = "next_review_at"
	// FieldInterval holds the string denoting the interval field in the database.
	FieldInterval = "interval"
	// FieldEaseFactor holds the string denoting the ease_factor field in the database.
	FieldEaseFactor = "ease_factor"
	// FieldTotalReviews holds the string denoting the total_reviews field in the database.
	FieldTotalReviews = "total_reviews"
	// FieldTotalSuccessful holds the string denoting the total_successful field in the database.
	FieldTotalSuccessful = "total_successful"
	// FieldStreak holds the string denoting the streak field in the database.
	FieldStreak = "streak"
	// FieldReviewsLast1d holds the string denoting the reviews_last_1d field in the database.
	FieldReviewsLast1d = "reviews_last_1d"
	// FieldReviewsLast3d holds the string denoting the reviews_last_3d field in the database.
	FieldReviewsLast3d = "reviews_last_3d"
	// FieldReviewsLast7d holds the string denoting the reviews_last_7d field in the database.
	FieldReviewsLast7d = "reviews_last_7d"
	// FieldAvgResponseTimeMs holds the string denoting the avg_response_time_ms field in the database.
	FieldAvgResponseTimeMs = "avg_response_time_ms"
	// FieldLastReviewAt holds the string denoting the last_review_at field in the database.
	FieldLastReviewAt = "last_review_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCard holds the string denoting the card edge name in mutations.
	EdgeCard = "card"
	// Table holds the table name of the state in the database.
	Table = "states"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "states"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_states"
	// CardTable is the table that holds the card relation/edge.
	CardTable = "states"
	// CardInverseTable is the table name for the Card entity.
	// It exists in this package in order to avoid circular dependency with the "card" package.
	CardInverseTable = "cards"
	// CardColumn is the table column denoting the card relation/edge.
	CardColumn = "card_states"
)

// Columns holds all SQL columns for state fields.
var Columns = []string{
	FieldID,
	FieldNextReviewAt,
	FieldInterval,
	FieldEaseFactor,
	FieldTotalReviews,
	FieldTotalSuccessful,
	FieldStreak,
	FieldReviewsLast1d,
	FieldReviewsLast3d,
	FieldReviewsLast7d,
	FieldAvgResponseTimeMs,
	FieldLastReviewAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "states"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"card_states",
	"user_states",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTotalReviews holds the default value on creation for the "total_reviews" field.
	DefaultTotalReviews int
	// DefaultTotalSuccessful holds the default value on creation for the "total_successful" field.
	DefaultTotalSuccessful int
	// DefaultStreak holds the default value on creation for the "streak" field.
	DefaultStreak int
	// DefaultReviewsLast1d holds the default value on creation for the "reviews_last_1d" field.
	DefaultReviewsLast1d int
	// DefaultReviewsLast3d holds the default value on creation for the "reviews_last_3d" field.
	DefaultReviewsLast3d int
	// DefaultReviewsLast7d holds the default value on creation for the "reviews_last_7d" field.
	DefaultReviewsLast7d int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the State queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNextReviewAt orders the results by the next_review_at field.
func ByNextReviewAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextReviewAt, opts...).ToFunc()
}

// ByInterval orders the results by the interval field.
func ByInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterval, opts...).ToFunc()
}

// ByEaseFactor orders the results by the ease_factor field.
func ByEaseFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEaseFactor, opts...).ToFunc()
}

// ByTotalReviews orders the results by the total_reviews field.
func ByTotalReviews(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReviews, opts...).ToFunc()
}

// ByTotalSuccessful orders the results by the total_successful field.
func ByTotalSuccessful(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSuccessful, opts...).ToFunc()
}

// ByStreak orders the results by the streak field.
func ByStreak(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreak, opts...).ToFunc()
}

// ByReviewsLast1d orders the results by the reviews_last_1d field.
func ByReviewsLast1d(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewsLast1d, opts...).ToFunc()
}

// ByReviewsLast3d orders the results by the reviews_last_3d field.
func ByReviewsLast3d(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewsLast3d, opts...).ToFunc()
}

// ByReviewsLast7d orders the results by the reviews_last_7d field.
func ByReviewsLast7d(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewsLast7d, opts...).ToFunc()
}

// ByAvgResponseTimeMs orders the results by the avg_response_time_ms field.
func ByAvgResponseTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvgResponseTimeMs, opts...).ToFunc()
}

// ByLastReviewAt orders the results by the last_review_at field.
func ByLastReviewAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastReviewAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCardField orders the results by card field.
func ByCardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCardStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CardInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CardTable, CardColumn),
	)
}
